app.constant('API', {
  URL: 'https://api.foursquare.com/v2/venues/search',
  CLIENT_ID: 'MF0VNZHVNNXEFJQPCXYEAUVEGNZ0OHK1K00NGSLLEV2DSYGC',
  CLIENT_SECRET: 'YGXTO1CQPD4M5LBEJBCEUN1FCEUBYNV2UYOFHDKMZFGPG4PU'
})
